name: AlathraWar
version: 1.1.4
api-version: 1.19
author: ShermansWorld
main: me.ShermansWorld.AlathraWar.Main
depend: [Vault, Towny, LuckPerms]

commands:
  war:
    description: used to create, delete, join and leave wars
    softdepend: [Vault, Towny, LuckPerms]
  siege:
    description: used to start, end, and view sieges
    softdepend: [Vault, Towny]