name: AlathraWar
version: 1.2.1
api-version: 1.19
author: ShermansWorld
main: me.ShermansWorld.AlathraWar.Main
depend: [Vault, Towny, LuckPerms]

commands:
  war:
    description: used to create, delete, join and leave wars
    softdepend: [Vault, Towny, LuckPerms]
  siege:
    description: used to start, end, and view sieges
    softdepend: [Vault, Towny]
  mercenary:
    description: Framework for handling mercenary work
    softdepend: [Vault, Towny]
    aliases:
      - merc
  assassin:
    description: Framework for handling assassin work
    softdepend: [Vault, Towny]
    aliases:
      - ass
      - assin
  contract:
    description: Framework for handling contracts
    softdepend: [Vault, Towny]
    aliases:
      - contracts