#Minimum time in days a player must have joined ago to join any war or event.
#Set to 0 to disable check
minimumPlayerAge: 4
#Minimum playtime in hours a player must have in hours to join a war/siege/raid
#Set to 0 to disable check
minimumPlayTime: 12
#How long should a bettering ram open a door (in seconds)
batteringRamEffectiveness: 10