name: AlathraWar
version: 1.1.3
api-version: 1.18
author: ShermansWorld
main: me.ShermansWorld.AlathraWar.Main

commands:
  war:
    description: used to create, delete, join and leave wars
    softdepend: [Vault, Towny]
  siege:
    description: used to start, end, and view sieges
    softdepend: [Vault, Towny]